version: '3.8'
name: 'league_tournament_manager'
services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    volumes:
      - ./bot/src:/app
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: postgres_container
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: DB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
      driver: local